#!/bin/bash

week=$(( $(date +%W) + 1 ))
[[ "$1" =~ [0-9]+ ]] && week=$1 && shift

until_week=$week
[[ "$1" =~ [0-9]+ ]] && until_week=$1 && shift

function monday() {
    local week=$1
    local year=${2:-$(date +%Y)}
    local fst_week_day=$(date -d $year-01-01 +%u)

    date -d "$year-01-01 -$((fst_week_day - 1)) day +$(($week - 1)) week" +%F
}

function sunday() {
    date -d "$(monday $*) +6 day" +%F
}


# defaults
header='# Weekly training records \n\n'
week_format='## %s \n\n'
project_format='### %s \n\n'
repo_format='#. %s \n'
commit_format='    + `[%h] _time_` — %s'
total_format='    In total: _human_time_\n'


# file with projects map and format options
file="./projects.map"
[[ "$1" =~ --projects ]] && file=${2:?"Expected projects map file!"} && shift 2
source "$file"
(( $? != 0 )) && exit

function list() {
	local week=$1
	shift
	local mon=$(date -d "`monday $week`" +%d.%m.%Y)
	local sun=$(date -d "`sunday $week`" +%d.%m.%Y)

	printf "$week_format" "Week $week ($mon — $sun)"

	for project_id in ${projects[@]}; do
		local project=( $(project $project_id) )
		local name=${project[0]//_/ }
		local repos=${project[@]:1}
		local repo_data=""

		for repo in ${repos[@]}; do
			cd "$prefix/$repo"
			local commits=$(gtm report -f "$commit_format" -t "$total_format" -w $week "$@")
			repo=${repo_format/\%s/"$repo"}
			[ "$commits" ] && repo_data="${repo_data}${repo}${commits}\n"
		done

		if [ "$repo_data" ]; then
			printf "$project_format" "$name"
			echo -e "$repo_data"
		fi
	done
}


starting_point=$(pwd)

printf "$header"

until (( $week > $until_week )); do
	list $week "$@"
	week=$(( week + 1 ))
done

cd $starting_point
